### ISSUE TITLE
Extra-opts config

### ISSUE THREAD

**Issue by jamesbeedy** [tengu-team/layer-openvpn#5]
My use case is such that I only want to push the route to the subnet, not dns, and not gateway.

I accomplish this by configuring openvpn charm to not push gateway and not push dns, and then adding these 2 lines to my dns server config:

push "route 10.50.2.0 255.255.255.0"
push "route 10.200.200.0 255.255.255.0"

How do you feel about possibly just changing the default for push-default-gateway=false, to include pushing the route to the private subnet, and just not pushing the gateway?

**Comment by merlijn-sebrechts** [comment]
Hi James


The behavior you're describing should be the current behavior. The charm
should automatically discover the private subnets and push them. I just
fixed an issue concerning this yesterday. Can you try out the beta channel
of `cs:~tengu-team/openvpn-5` and let me know if that works out for you?

If this doesn't fix your issue, can you show the output of `route -n` and
`ifconfig` on the openvpn server?

**Comment by jamesbeedy** [comment]
@galgalesh awesome! rev5 works great!
