### ISSUE TITLE
push-default-gateway: false - doesn't push routes correctly

### ISSUE THREAD

**Issue by jamesbeedy** [tengu-team/layer-openvpn#9]
Connectivity issues arise when 'push-default-gateway' config is set to 'false'. (More to come)

**Comment by merlijn-sebrechts** [comment]
I can confirm this is an issue with `cs:tengu-team/openvpn-6`. This is introduced by the randomization of the tun network address.

Workaround 1.: Use `cs:tengu-team/openvpn-5`
Workaround 2.: Change the `server` option in the openvpn server config file to `10.200.200.0 255.255.255.0`

**Comment by merlijn-sebrechts** [comment]
This is the culprit:

https://github.com/tengu-team/layer-openvpn/blob/799b5202248ffafc455ed296d8a00250373466f6/templates/init.pp#L148

```puppet
firewall { '125 POSTROUTING':
  table    => 'nat',
  proto    => 'all',
  chain    => 'POSTROUTING',
  source   => "10.200.200.0/24",
  jump     => 'MASQUERADE',
}
```

Hardcoded ip in firewall rule

**Comment by jamesbeedy** [comment]
@galgalesh Nice find!!!! Lets get this baby patched and released!

**Comment by jamesbeedy** [comment]
@galgalesh whats in master is still broken in the sense that it still isn't adding the route correctly when push-default-gateway: false .... possibly there is another component we aren't looking at?

**Comment by merlijn-sebrechts** [comment]
@jamesbeedy
Can you test cs:~tengu-team/openvpn-7 and let me know if it works? If it doesn't, let me know how I can reproduce your issue?

**Comment by merlijn-sebrechts** [comment]
(how I can reproduce your issue on aws)

**Comment by jamesbeedy** [comment]
@galgalesh just deploy the charm with push-default-gateway: false. Then connect your tunnleblick and try to ping the private ip address of something else on the private subnet.

I think I have a fix in place now. Give me five mins.

**Comment by merlijn-sebrechts** [comment]
Hi James

The latest version of the OpenVPN Charm pushes all routes of the VPN server to the clients by default, both when `push-default-gateway` is true and false.

This should fix your issue, and this also gives you an easy workaround if you're still having issues: just add a static route on the machine the VPN server runs on and it will be pushed to all clients the next time the charm reconfigures. [You can force the charm to reconfigure by adding another client to `clients`].

I'm thus closing this issue. Feel free to re-open it or add a new one if you're still having issues.
